apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cnn-serving
  namespace: default
spec:
  template:
    metadata:
    spec:
      containerConcurrency: 1000
      containers:
        - image: kind.local/server-cnn-serving:1.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 640M
            limits:
              cpu: 1
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1000"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1h"
